
#ifndef SRS_FMOD_TYPES_H
#define SRS_FMOD_TYPES_H

enum SRS_FMOD_ENCODER_CODEC{
	SRS_FMOD_ENCODER_CODEC_NONE = 0,
	SRS_FMOD_ENCODER_CODEC_MP3,
	SRS_FMOD_ENCODER_CODEC_OGG,
	SRS_FMOD_ENCODER_CODEC_WAV
};

#endif
